In [1]:
import sys
sys.path.append('/home/dnlab/Jupyter-Bitcoin/Heuristics/ExperimentSpeed/')
import pandas as pd
import test_cluster_db_query as cdq
import test_db_query as dq

In [2]:
root_addr_df = pd.read_csv('/home/dnlab/DataHDD/AddressTag.csv')[['ClusterName', 'Category', 'Address']]
root_addr_df

            ClusterName        Category                             Address
0                  0day  darknet market  17Bccs6eJAKsXHeopcH5FCt7o1FdCk1Xw7
1           10xBitco.in        gambling   1rH4vGpf5LEgCvUxXgRycGrQ5ahsxXB2F
2       12DailyCoin.com            scam  1Kd9zuLiJ5mbz6YD7a8nQiiAXvPuveUyRL
3             1coin.com        exchange  14zRXp2AZ8yxXzPXJ5gAirmgAxJdUZiVut
4             1Hash.com     mining pool  1F1xcRt8H8Wa623KqmkEontwAAVqDSAWCV
...                 ...             ...                                 ...
70323  MinersCenter.com    Old/historic  16C2LU2fnfYXYCGN6AMNsE326mdcZDXu6S
70324  MinersCenter.com    Old/historic  1Aucrq5wcJFeJaASrvCFC148SEvUT59nMK
70325  MinersCenter.com    Old/historic  1NrQUKwQfyUo2j8xiUWhPvtNahfcAnSacH
70326  MinersCenter.com    Old/historic  1BvEvZecd6RCarNdryN393Z2YZqFdYwvEe
70327  MinersCenter.com    Old/historic  1K1XbKQmB7PxLFLN3dQYHcDp6z1rtTbWRK

[70328 rows x 3 columns]

In [5]:
root_addr_df['addr'] = root_addr_df['Address'].map(lambda x: dq.get_addrid_from_addr(x))
root_addr_df = root_addr_df.dropna(axis=0)

<ipython-input-5-60b43552831b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  root_addr_df['addr'] = root_addr_df['Address'].map(lambda x: dq.get_addrid_from_addr(x))

In [6]:
root_addr_df

,ClusterName,Category,Address,addr
0,0day,darknet market,17Bccs6eJAKsXHeopcH5FCt7o1FdCk1Xw7,210561803
1,10xBitco.in,gambling,1rH4vGpf5LEgCvUxXgRycGrQ5ahsxXB2F,40136091
2,12DailyCoin.com,scam,1Kd9zuLiJ5mbz6YD7a8nQiiAXvPuveUyRL,118097456
3,1coin.com,exchange,14zRXp2AZ8yxXzPXJ5gAirmgAxJdUZiVut,27546014
4,1Hash.com,mining pool,1F1xcRt8H8Wa623KqmkEontwAAVqDSAWCV,128542181
...,...,...,...,...
70323,MinersCenter.com,Old/historic,16C2LU2fnfYXYCGN6AMNsE326mdcZDXu6S,163572350
70324,MinersCenter.com,Old/historic,1Aucrq5wcJFeJaASrvCFC148SEvUT59nMK,164647313
70325,MinersCenter.com,Old/historic,1NrQUKwQfyUo2j8xiUWhPvtNahfcAnSacH,151498681
70326,MinersCenter.com,Old/historic,1BvEvZecd6RCarNdryN393Z2YZqFdYwvEe,148055976
70327,MinersCenter.com,Old/historic,1K1XbKQmB7PxLFLN3dQYHcDp6z1rtTbWRK,162941851

In [7]:
root_addr_df.addr = root_addr_df.addr.astype('int32')

In [8]:
root_addr_df

,ClusterName,Category,Address,addr
0,0day,darknet market,17Bccs6eJAKsXHeopcH5FCt7o1FdCk1Xw7,210561803
1,10xBitco.in,gambling,1rH4vGpf5LEgCvUxXgRycGrQ5ahsxXB2F,40136091
2,12DailyCoin.com,scam,1Kd9zuLiJ5mbz6YD7a8nQiiAXvPuveUyRL,118097456
3,1coin.com,exchange,14zRXp2AZ8yxXzPXJ5gAirmgAxJdUZiVut,27546014
4,1Hash.com,mining pool,1F1xcRt8H8Wa623KqmkEontwAAVqDSAWCV,128542181
...,...,...,...,...
70323,MinersCenter.com,Old/historic,16C2LU2fnfYXYCGN6AMNsE326mdcZDXu6S,163572350
70324,MinersCenter.com,Old/historic,1Aucrq5wcJFeJaASrvCFC148SEvUT59nMK,164647313
70325,MinersCenter.com,Old/historic,1NrQUKwQfyUo2j8xiUWhPvtNahfcAnSacH,151498681
70326,MinersCenter.com,Old/historic,1BvEvZecd6RCarNdryN393Z2YZqFdYwvEe,148055976
70327,MinersCenter.com,Old/historic,1K1XbKQmB7PxLFLN3dQYHcDp6z1rtTbWRK,162941851

In [9]:
len(root_addr_df[root_addr_df['addr'] == 1])

1

In [10]:
mi_df= pd.read_csv('/home/dnlab/DataHDD/cluster_result/cluster.csv')
data_condition =mi_df['number'] != -1
mi_df = mi_df[data_condition]
mi_df= mi_df.rename(columns={"address": "addr"})
mi_df

                addr     number
79                79       1936
172              172        859
193              193        193
242              242        242
256              256        193
...              ...        ...
691806336  691806336  691783473
691806492  691806492  691375532
691806710  691806710  680462910
691806713  691806713  691737711
691806720  691806720  674695649

[418493080 rows x 2 columns]

In [11]:
#mi_df = mi_df.sort_values('number')
#mi_df

In [12]:
mi_group = mi_df.groupby('number')
mi_dict = []
#{'Group':1234, 'Tag':[], 'intxNum':12, 'outTx':13, 'InValue':13, 'OutValue':123}

In [13]:

import csv

In [ ]:
cluster_list = []
count = 0
with open('/home/dnlab/DataHDD/all_info.csv', 'w', newline='') as csvfile:
    fieldnames = ['group', 'Category','num_in_tx','num_out_tx', \
                  'in_value', 'out_value', 'balance', \
                  'smallest_addr', 'ClusterName', 'len']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for cluster_number, addr_group in mi_group:
        if len(mi_group) > 100000:
            print("OVER 100000 the length of addr_list:", len(addr_group))
        addr_dict = {'group':cluster_number, 'Category':[], 'num_in_tx':0, \
                     'num_out_tx':0, 'in_value':0, 'out_value':0, 'balance':0,\
                     'smallest_addr':addr_group.reset_index().iloc[0]['addr'],\
                     'ClusterName':[],'len': len(addr_group)}
        addr_list = addr_group['addr'].to_list()


        if len(addr_list) > 10000:
            print("query start", len(addr_list))
            
        addr_dict['num_in_tx'] = dq.count_all_tx_in(addr_list)[0]
        addr_dict['num_out_tx'] = dq.count_all_tx_out(addr_list)[0]
        addr_dict['in_value'] = dq.sum_all_invalue(addr_list)[0]
        addr_dict['out_value'] = dq.sum_all_outvalue(addr_list)[0]
        addr_dict['balance'] = addr_dict['out_value'] - addr_dict['in_value']
        
        if len(addr_list) > 10000:
            print("join_start:", len(addr_list))   
        join_df = pd.merge(addr_group, root_addr_df,how = 'inner', on=['addr'])

        category = join_df['Category'].to_list()
        addr_dict['Category'].append(category) 

        cluster_name = join_df['ClusterName'].to_list()
        addr_dict['ClusterName'].append(cluster_name) 

        writer.writerow(addr_dict)
        if count % 100000== 0:
            print(count)
        count += 1